version: '3.8'

services:
  postgres-db:
    container_name: postgres_auth
    image: postgis/postgis:15-3.3  
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rent_hub_auth
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - renthub
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - renthub
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:root@postgres_auth:5432/rent_hub_auth?sslmode=disable", "up"]

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - renthub
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  auth:
    container_name: auth
    build: .
    ports:
      - "4444:4444"
      - "5555:5555"
    networks:
     - renthub
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_started
      redis:
        condition: service_healthy

networks:
  renthub:

volumes:
  db:
  redis-data:
