// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: top-properties.proto

package top_properties

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTopPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Top property ID
}

func (x *GetTopPropertyReq) Reset() {
	*x = GetTopPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPropertyReq) ProtoMessage() {}

func (x *GetTopPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPropertyReq.ProtoReflect.Descriptor instead.
func (*GetTopPropertyReq) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{0}
}

func (x *GetTopPropertyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTopPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopProperty *TopProperty `protobuf:"bytes,1,opt,name=top_property,json=topProperty,proto3" json:"top_property,omitempty"`
}

func (x *GetTopPropertyRes) Reset() {
	*x = GetTopPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopPropertyRes) ProtoMessage() {}

func (x *GetTopPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopPropertyRes.ProtoReflect.Descriptor instead.
func (*GetTopPropertyRes) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{1}
}

func (x *GetTopPropertyRes) GetTopProperty() *TopProperty {
	if x != nil {
		return x.TopProperty
	}
	return nil
}

type GetAllTopPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetAllTopPropertyReq) Reset() {
	*x = GetAllTopPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTopPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopPropertyReq) ProtoMessage() {}

func (x *GetAllTopPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopPropertyReq.ProtoReflect.Descriptor instead.
func (*GetAllTopPropertyReq) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllTopPropertyReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllTopPropertyReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetAllTopPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopProperties []*TopProperty `protobuf:"bytes,1,rep,name=top_properties,json=topProperties,proto3" json:"top_properties,omitempty"`
}

func (x *GetAllTopPropertyRes) Reset() {
	*x = GetAllTopPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllTopPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllTopPropertyRes) ProtoMessage() {}

func (x *GetAllTopPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllTopPropertyRes.ProtoReflect.Descriptor instead.
func (*GetAllTopPropertyRes) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllTopPropertyRes) GetTopProperties() []*TopProperty {
	if x != nil {
		return x.TopProperties
	}
	return nil
}

type CreateTopPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyId string `protobuf:"bytes,1,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TariffName string `protobuf:"bytes,3,opt,name=tariff_name,json=tariffName,proto3" json:"tariff_name,omitempty"`
}

func (x *CreateTopPropertyReq) Reset() {
	*x = CreateTopPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopPropertyReq) ProtoMessage() {}

func (x *CreateTopPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopPropertyReq.ProtoReflect.Descriptor instead.
func (*CreateTopPropertyReq) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopPropertyReq) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *CreateTopPropertyReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTopPropertyReq) GetTariffName() string {
	if x != nil {
		return x.TariffName
	}
	return ""
}

type CreateTopPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Top property ID
}

func (x *CreateTopPropertyRes) Reset() {
	*x = CreateTopPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopPropertyRes) ProtoMessage() {}

func (x *CreateTopPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopPropertyRes.ProtoReflect.Descriptor instead.
func (*CreateTopPropertyRes) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTopPropertyRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTopPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertyId string `protobuf:"bytes,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate  string `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate    string `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TariffName string `protobuf:"bytes,6,opt,name=tariff_name,json=tariffName,proto3" json:"tariff_name,omitempty"`
}

func (x *UpdateTopPropertyReq) Reset() {
	*x = UpdateTopPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTopPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopPropertyReq) ProtoMessage() {}

func (x *UpdateTopPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopPropertyReq.ProtoReflect.Descriptor instead.
func (*UpdateTopPropertyReq) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTopPropertyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTopPropertyReq) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *UpdateTopPropertyReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTopPropertyReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *UpdateTopPropertyReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *UpdateTopPropertyReq) GetTariffName() string {
	if x != nil {
		return x.TariffName
	}
	return ""
}

type UpdateTopPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateTopPropertyRes) Reset() {
	*x = UpdateTopPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTopPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopPropertyRes) ProtoMessage() {}

func (x *UpdateTopPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopPropertyRes.ProtoReflect.Descriptor instead.
func (*UpdateTopPropertyRes) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTopPropertyRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTopPropertyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteTopPropertyReq) Reset() {
	*x = DeleteTopPropertyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTopPropertyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopPropertyReq) ProtoMessage() {}

func (x *DeleteTopPropertyReq) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopPropertyReq.ProtoReflect.Descriptor instead.
func (*DeleteTopPropertyReq) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTopPropertyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTopPropertyRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteTopPropertyRes) Reset() {
	*x = DeleteTopPropertyRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTopPropertyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopPropertyRes) ProtoMessage() {}

func (x *DeleteTopPropertyRes) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopPropertyRes.ProtoReflect.Descriptor instead.
func (*DeleteTopPropertyRes) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTopPropertyRes) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TopProperty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PropertyId string `protobuf:"bytes,2,opt,name=property_id,json=propertyId,proto3" json:"property_id,omitempty"`
	UserId     string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate  string `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate    string `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TariffName string `protobuf:"bytes,6,opt,name=tariff_name,json=tariffName,proto3" json:"tariff_name,omitempty"`
	CreatedAt  string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *TopProperty) Reset() {
	*x = TopProperty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_top_properties_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProperty) ProtoMessage() {}

func (x *TopProperty) ProtoReflect() protoreflect.Message {
	mi := &file_top_properties_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProperty.ProtoReflect.Descriptor instead.
func (*TopProperty) Descriptor() ([]byte, []int) {
	return file_top_properties_proto_rawDescGZIP(), []int{10}
}

func (x *TopProperty) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopProperty) GetPropertyId() string {
	if x != nil {
		return x.PropertyId
	}
	return ""
}

func (x *TopProperty) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopProperty) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *TopProperty) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TopProperty) GetTariffName() string {
	if x != nil {
		return x.TariffName
	}
	return ""
}

func (x *TopProperty) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_top_properties_proto protoreflect.FileDescriptor

var file_top_properties_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x6f, 0x70, 0x2d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x12, 0x3e, 0x0a, 0x0c, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x52, 0x0b, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x22, 0x40, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x22, 0x5a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x42, 0x0a, 0x0e, 0x74, 0x6f,
	0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52,
	0x0d, 0x74, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x71,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65,
	0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x69, 0x66, 0x66,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61, 0x72,
	0x69, 0x66, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x69, 0x66,
	0x66, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x61,
	0x72, 0x69, 0x66, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xbb, 0x03, 0x0a, 0x14, 0x54, 0x6f, 0x70, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x74, 0x6f, 0x70,
	0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x54, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54,
	0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e,
	0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x52, 0x65, 0x73, 0x12, 0x54, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e,
	0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12, 0x54, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x73, 0x12,
	0x54, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f,
	0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x52, 0x65, 0x73, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_top_properties_proto_rawDescOnce sync.Once
	file_top_properties_proto_rawDescData = file_top_properties_proto_rawDesc
)

func file_top_properties_proto_rawDescGZIP() []byte {
	file_top_properties_proto_rawDescOnce.Do(func() {
		file_top_properties_proto_rawDescData = protoimpl.X.CompressGZIP(file_top_properties_proto_rawDescData)
	})
	return file_top_properties_proto_rawDescData
}

var file_top_properties_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_top_properties_proto_goTypes = []any{
	(*GetTopPropertyReq)(nil),    // 0: top_properties.GetTopPropertyReq
	(*GetTopPropertyRes)(nil),    // 1: top_properties.GetTopPropertyRes
	(*GetAllTopPropertyReq)(nil), // 2: top_properties.GetAllTopPropertyReq
	(*GetAllTopPropertyRes)(nil), // 3: top_properties.GetAllTopPropertyRes
	(*CreateTopPropertyReq)(nil), // 4: top_properties.CreateTopPropertyReq
	(*CreateTopPropertyRes)(nil), // 5: top_properties.CreateTopPropertyRes
	(*UpdateTopPropertyReq)(nil), // 6: top_properties.UpdateTopPropertyReq
	(*UpdateTopPropertyRes)(nil), // 7: top_properties.UpdateTopPropertyRes
	(*DeleteTopPropertyReq)(nil), // 8: top_properties.DeleteTopPropertyReq
	(*DeleteTopPropertyRes)(nil), // 9: top_properties.DeleteTopPropertyRes
	(*TopProperty)(nil),          // 10: top_properties.TopProperty
}
var file_top_properties_proto_depIdxs = []int32{
	10, // 0: top_properties.GetTopPropertyRes.top_property:type_name -> top_properties.TopProperty
	10, // 1: top_properties.GetAllTopPropertyRes.top_properties:type_name -> top_properties.TopProperty
	0,  // 2: top_properties.TopPropertiesService.Get:input_type -> top_properties.GetTopPropertyReq
	2,  // 3: top_properties.TopPropertiesService.GetAll:input_type -> top_properties.GetAllTopPropertyReq
	4,  // 4: top_properties.TopPropertiesService.Create:input_type -> top_properties.CreateTopPropertyReq
	6,  // 5: top_properties.TopPropertiesService.Update:input_type -> top_properties.UpdateTopPropertyReq
	8,  // 6: top_properties.TopPropertiesService.Delete:input_type -> top_properties.DeleteTopPropertyReq
	1,  // 7: top_properties.TopPropertiesService.Get:output_type -> top_properties.GetTopPropertyRes
	3,  // 8: top_properties.TopPropertiesService.GetAll:output_type -> top_properties.GetAllTopPropertyRes
	5,  // 9: top_properties.TopPropertiesService.Create:output_type -> top_properties.CreateTopPropertyRes
	7,  // 10: top_properties.TopPropertiesService.Update:output_type -> top_properties.UpdateTopPropertyRes
	9,  // 11: top_properties.TopPropertiesService.Delete:output_type -> top_properties.DeleteTopPropertyRes
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_top_properties_proto_init() }
func file_top_properties_proto_init() {
	if File_top_properties_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_top_properties_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetTopPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetTopPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllTopPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllTopPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTopPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*CreateTopPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTopPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateTopPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTopPropertyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteTopPropertyRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_top_properties_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TopProperty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_top_properties_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_top_properties_proto_goTypes,
		DependencyIndexes: file_top_properties_proto_depIdxs,
		MessageInfos:      file_top_properties_proto_msgTypes,
	}.Build()
	File_top_properties_proto = out.File
	file_top_properties_proto_rawDesc = nil
	file_top_properties_proto_goTypes = nil
	file_top_properties_proto_depIdxs = nil
}
